// This file is automatically generated by qtc from "adminpage.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line adminpage.qtpl:1
package templates

//line adminpage.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line adminpage.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line adminpage.qtpl:2
type AdminPage struct {
}

//line adminpage.qtpl:7
func (p *AdminPage) StreamMetaInfo(qw422016 *qt422016.Writer) {
	//line adminpage.qtpl:7
	qw422016.N().S(`
    <title>Admin page</title>
`)
//line adminpage.qtpl:9
}

//line adminpage.qtpl:9
func (p *AdminPage) WriteMetaInfo(qq422016 qtio422016.Writer) {
	//line adminpage.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line adminpage.qtpl:9
	p.StreamMetaInfo(qw422016)
	//line adminpage.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line adminpage.qtpl:9
}

//line adminpage.qtpl:9
func (p *AdminPage) MetaInfo() string {
	//line adminpage.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
	//line adminpage.qtpl:9
	p.WriteMetaInfo(qb422016)
	//line adminpage.qtpl:9
	qs422016 := string(qb422016.B)
	//line adminpage.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
	//line adminpage.qtpl:9
	return qs422016
//line adminpage.qtpl:9
}

//line adminpage.qtpl:11
func (p *AdminPage) StreamBody(qw422016 *qt422016.Writer) {
	//line adminpage.qtpl:11
	qw422016.N().S(`
    <div class="admin-page">
        <admin-page/>
    </div>
`)
//line adminpage.qtpl:15
}

//line adminpage.qtpl:15
func (p *AdminPage) WriteBody(qq422016 qtio422016.Writer) {
	//line adminpage.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line adminpage.qtpl:15
	p.StreamBody(qw422016)
	//line adminpage.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line adminpage.qtpl:15
}

//line adminpage.qtpl:15
func (p *AdminPage) Body() string {
	//line adminpage.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
	//line adminpage.qtpl:15
	p.WriteBody(qb422016)
	//line adminpage.qtpl:15
	qs422016 := string(qb422016.B)
	//line adminpage.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
	//line adminpage.qtpl:15
	return qs422016
//line adminpage.qtpl:15
}

//line adminpage.qtpl:17
func (p *AdminPage) StreamCSSExternal(qw422016 *qt422016.Writer) {
	//line adminpage.qtpl:17
	qw422016.N().S(`
`)
//line adminpage.qtpl:18
}

//line adminpage.qtpl:18
func (p *AdminPage) WriteCSSExternal(qq422016 qtio422016.Writer) {
	//line adminpage.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line adminpage.qtpl:18
	p.StreamCSSExternal(qw422016)
	//line adminpage.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line adminpage.qtpl:18
}

//line adminpage.qtpl:18
func (p *AdminPage) CSSExternal() string {
	//line adminpage.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
	//line adminpage.qtpl:18
	p.WriteCSSExternal(qb422016)
	//line adminpage.qtpl:18
	qs422016 := string(qb422016.B)
	//line adminpage.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
	//line adminpage.qtpl:18
	return qs422016
//line adminpage.qtpl:18
}

//line adminpage.qtpl:20
func (p *AdminPage) StreamScriptExternal(qw422016 *qt422016.Writer) {
	//line adminpage.qtpl:20
	qw422016.N().S(`
`)
//line adminpage.qtpl:21
}

//line adminpage.qtpl:21
func (p *AdminPage) WriteScriptExternal(qq422016 qtio422016.Writer) {
	//line adminpage.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line adminpage.qtpl:21
	p.StreamScriptExternal(qw422016)
	//line adminpage.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line adminpage.qtpl:21
}

//line adminpage.qtpl:21
func (p *AdminPage) ScriptExternal() string {
	//line adminpage.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
	//line adminpage.qtpl:21
	p.WriteScriptExternal(qb422016)
	//line adminpage.qtpl:21
	qs422016 := string(qb422016.B)
	//line adminpage.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
	//line adminpage.qtpl:21
	return qs422016
//line adminpage.qtpl:21
}
