// This file is automatically generated by qtc from "hompage.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line hompage.qtpl:1
package templates

//line hompage.qtpl:1
import "go-basic-rest-api/models"

//line hompage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line hompage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line hompage.qtpl:4
type HomePage struct {
	User models.User
}

//line hompage.qtpl:9
func (p *HomePage) StreamTitle(qw422016 *qt422016.Writer) {
	//line hompage.qtpl:9
	qw422016.N().S(`
	Beranda `)
	//line hompage.qtpl:10
	qw422016.E().S(p.User.Username)
	//line hompage.qtpl:10
	qw422016.N().S(`
`)
//line hompage.qtpl:11
}

//line hompage.qtpl:11
func (p *HomePage) WriteTitle(qq422016 qtio422016.Writer) {
	//line hompage.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line hompage.qtpl:11
	p.StreamTitle(qw422016)
	//line hompage.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line hompage.qtpl:11
}

//line hompage.qtpl:11
func (p *HomePage) Title() string {
	//line hompage.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
	//line hompage.qtpl:11
	p.WriteTitle(qb422016)
	//line hompage.qtpl:11
	qs422016 := string(qb422016.B)
	//line hompage.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
	//line hompage.qtpl:11
	return qs422016
//line hompage.qtpl:11
}

//line hompage.qtpl:13
func (p *HomePage) StreamBody(qw422016 *qt422016.Writer) {
	//line hompage.qtpl:13
	qw422016.N().S(`
    <div class="home-page">
        <user-home></user-home>  
    </div>
`)
//line hompage.qtpl:17
}

//line hompage.qtpl:17
func (p *HomePage) WriteBody(qq422016 qtio422016.Writer) {
	//line hompage.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line hompage.qtpl:17
	p.StreamBody(qw422016)
	//line hompage.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line hompage.qtpl:17
}

//line hompage.qtpl:17
func (p *HomePage) Body() string {
	//line hompage.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line hompage.qtpl:17
	p.WriteBody(qb422016)
	//line hompage.qtpl:17
	qs422016 := string(qb422016.B)
	//line hompage.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line hompage.qtpl:17
	return qs422016
//line hompage.qtpl:17
}

//line hompage.qtpl:19
func (p *HomePage) StreamCSSExternal(qw422016 *qt422016.Writer) {
	//line hompage.qtpl:19
	qw422016.N().S(`
`)
//line hompage.qtpl:20
}

//line hompage.qtpl:20
func (p *HomePage) WriteCSSExternal(qq422016 qtio422016.Writer) {
	//line hompage.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line hompage.qtpl:20
	p.StreamCSSExternal(qw422016)
	//line hompage.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line hompage.qtpl:20
}

//line hompage.qtpl:20
func (p *HomePage) CSSExternal() string {
	//line hompage.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
	//line hompage.qtpl:20
	p.WriteCSSExternal(qb422016)
	//line hompage.qtpl:20
	qs422016 := string(qb422016.B)
	//line hompage.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
	//line hompage.qtpl:20
	return qs422016
//line hompage.qtpl:20
}

//line hompage.qtpl:22
func (p *HomePage) StreamScriptExternal(qw422016 *qt422016.Writer) {
	//line hompage.qtpl:22
	qw422016.N().S(`
`)
//line hompage.qtpl:23
}

//line hompage.qtpl:23
func (p *HomePage) WriteScriptExternal(qq422016 qtio422016.Writer) {
	//line hompage.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line hompage.qtpl:23
	p.StreamScriptExternal(qw422016)
	//line hompage.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line hompage.qtpl:23
}

//line hompage.qtpl:23
func (p *HomePage) ScriptExternal() string {
	//line hompage.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
	//line hompage.qtpl:23
	p.WriteScriptExternal(qb422016)
	//line hompage.qtpl:23
	qs422016 := string(qb422016.B)
	//line hompage.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
	//line hompage.qtpl:23
	return qs422016
//line hompage.qtpl:23
}
