// This file is automatically generated by qtc from "indexpage.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line indexpage.qtpl:1
package templates

//line indexpage.qtpl:1
import "go-basic-rest-api/models"

//line indexpage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line indexpage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line indexpage.qtpl:4
type IndexPage struct {
	Users models.Users
}

//line indexpage.qtpl:9
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line indexpage.qtpl:9
	qw422016.N().S(`
	Todos Websites
`)
//line indexpage.qtpl:11
}

//line indexpage.qtpl:11
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line indexpage.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line indexpage.qtpl:11
	p.StreamTitle(qw422016)
	//line indexpage.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line indexpage.qtpl:11
}

//line indexpage.qtpl:11
func (p *IndexPage) Title() string {
	//line indexpage.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
	//line indexpage.qtpl:11
	p.WriteTitle(qb422016)
	//line indexpage.qtpl:11
	qs422016 := string(qb422016.B)
	//line indexpage.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
	//line indexpage.qtpl:11
	return qs422016
//line indexpage.qtpl:11
}

//line indexpage.qtpl:13
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
	//line indexpage.qtpl:13
	qw422016.N().S(`
    <div class="login-page">
        <form-login></form-login>  
    </div>
`)
//line indexpage.qtpl:17
}

//line indexpage.qtpl:17
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
	//line indexpage.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line indexpage.qtpl:17
	p.StreamBody(qw422016)
	//line indexpage.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line indexpage.qtpl:17
}

//line indexpage.qtpl:17
func (p *IndexPage) Body() string {
	//line indexpage.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line indexpage.qtpl:17
	p.WriteBody(qb422016)
	//line indexpage.qtpl:17
	qs422016 := string(qb422016.B)
	//line indexpage.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line indexpage.qtpl:17
	return qs422016
//line indexpage.qtpl:17
}
