// This file is automatically generated by qtc from "settingpage.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line settingpage.qtpl:1
package templates

//line settingpage.qtpl:1
import "go-basic-rest-api/models"

//line settingpage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line settingpage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line settingpage.qtpl:4
type SettingPage struct {
	User     models.User
	UserJSON []byte
}

//line settingpage.qtpl:10
func (p *SettingPage) StreamMetaInfo(qw422016 *qt422016.Writer) {
	//line settingpage.qtpl:10
	qw422016.N().S(`
    <title>Setting profile `)
	//line settingpage.qtpl:11
	qw422016.E().S(p.User.Name)
	//line settingpage.qtpl:11
	qw422016.N().S(`</title>
    <meta name="og:title" content="Setting profile `)
	//line settingpage.qtpl:12
	qw422016.E().S(p.User.Name)
	//line settingpage.qtpl:12
	qw422016.N().S(`"/>
    <meta name="og:type" content="article"/>
    <meta name="og:description" content="Setting profile `)
	//line settingpage.qtpl:14
	qw422016.E().S(p.User.Name)
	//line settingpage.qtpl:14
	qw422016.N().S(`"/>
`)
//line settingpage.qtpl:15
}

//line settingpage.qtpl:15
func (p *SettingPage) WriteMetaInfo(qq422016 qtio422016.Writer) {
	//line settingpage.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line settingpage.qtpl:15
	p.StreamMetaInfo(qw422016)
	//line settingpage.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line settingpage.qtpl:15
}

//line settingpage.qtpl:15
func (p *SettingPage) MetaInfo() string {
	//line settingpage.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
	//line settingpage.qtpl:15
	p.WriteMetaInfo(qb422016)
	//line settingpage.qtpl:15
	qs422016 := string(qb422016.B)
	//line settingpage.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
	//line settingpage.qtpl:15
	return qs422016
//line settingpage.qtpl:15
}

//line settingpage.qtpl:17
func (p *SettingPage) StreamBody(qw422016 *qt422016.Writer) {
	//line settingpage.qtpl:17
	qw422016.N().S(`
    <div class="setting-page">
        <settings-user user="`)
	//line settingpage.qtpl:19
	qw422016.E().V(string(p.UserJSON))
	//line settingpage.qtpl:19
	qw422016.N().S(`"/>
    </div>
`)
//line settingpage.qtpl:21
}

//line settingpage.qtpl:21
func (p *SettingPage) WriteBody(qq422016 qtio422016.Writer) {
	//line settingpage.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line settingpage.qtpl:21
	p.StreamBody(qw422016)
	//line settingpage.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line settingpage.qtpl:21
}

//line settingpage.qtpl:21
func (p *SettingPage) Body() string {
	//line settingpage.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
	//line settingpage.qtpl:21
	p.WriteBody(qb422016)
	//line settingpage.qtpl:21
	qs422016 := string(qb422016.B)
	//line settingpage.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
	//line settingpage.qtpl:21
	return qs422016
//line settingpage.qtpl:21
}

//line settingpage.qtpl:23
func (p *SettingPage) StreamCSSExternal(qw422016 *qt422016.Writer) {
	//line settingpage.qtpl:23
	qw422016.N().S(`
`)
//line settingpage.qtpl:24
}

//line settingpage.qtpl:24
func (p *SettingPage) WriteCSSExternal(qq422016 qtio422016.Writer) {
	//line settingpage.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line settingpage.qtpl:24
	p.StreamCSSExternal(qw422016)
	//line settingpage.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line settingpage.qtpl:24
}

//line settingpage.qtpl:24
func (p *SettingPage) CSSExternal() string {
	//line settingpage.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
	//line settingpage.qtpl:24
	p.WriteCSSExternal(qb422016)
	//line settingpage.qtpl:24
	qs422016 := string(qb422016.B)
	//line settingpage.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
	//line settingpage.qtpl:24
	return qs422016
//line settingpage.qtpl:24
}

//line settingpage.qtpl:26
func (p *SettingPage) StreamScriptExternal(qw422016 *qt422016.Writer) {
	//line settingpage.qtpl:26
	qw422016.N().S(`
`)
//line settingpage.qtpl:27
}

//line settingpage.qtpl:27
func (p *SettingPage) WriteScriptExternal(qq422016 qtio422016.Writer) {
	//line settingpage.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line settingpage.qtpl:27
	p.StreamScriptExternal(qw422016)
	//line settingpage.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line settingpage.qtpl:27
}

//line settingpage.qtpl:27
func (p *SettingPage) ScriptExternal() string {
	//line settingpage.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
	//line settingpage.qtpl:27
	p.WriteScriptExternal(qb422016)
	//line settingpage.qtpl:27
	qs422016 := string(qb422016.B)
	//line settingpage.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
	//line settingpage.qtpl:27
	return qs422016
//line settingpage.qtpl:27
}
