// This file is automatically generated by qtc from "todopage.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line todopage.qtpl:1
package templates

//line todopage.qtpl:1
import "go-basic-rest-api/models"

//line todopage.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line todopage.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line todopage.qtpl:4
type TodoPage struct {
	Todo     models.Todo
	UserJSON []byte
}

//line todopage.qtpl:10
func (p *TodoPage) StreamMetaInfo(qw422016 *qt422016.Writer) {
	//line todopage.qtpl:10
	qw422016.N().S(`
    <title>Todo `)
	//line todopage.qtpl:11
	qw422016.E().S(p.Todo.Name)
	//line todopage.qtpl:11
	qw422016.N().S(`</title>
    <meta name="og:title" content="`)
	//line todopage.qtpl:12
	qw422016.E().S(p.Todo.Name)
	//line todopage.qtpl:12
	qw422016.N().S(`"/>
    <meta name="og:type" content="article"/>
    <meta name="turbolinks-visit-control" content="reload">
`)
//line todopage.qtpl:15
}

//line todopage.qtpl:15
func (p *TodoPage) WriteMetaInfo(qq422016 qtio422016.Writer) {
	//line todopage.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line todopage.qtpl:15
	p.StreamMetaInfo(qw422016)
	//line todopage.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line todopage.qtpl:15
}

//line todopage.qtpl:15
func (p *TodoPage) MetaInfo() string {
	//line todopage.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
	//line todopage.qtpl:15
	p.WriteMetaInfo(qb422016)
	//line todopage.qtpl:15
	qs422016 := string(qb422016.B)
	//line todopage.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
	//line todopage.qtpl:15
	return qs422016
//line todopage.qtpl:15
}

//line todopage.qtpl:17
func (p *TodoPage) StreamBody(qw422016 *qt422016.Writer) {
	//line todopage.qtpl:17
	qw422016.N().S(`
    <div class="todo-page">
        <div class="nav-wrp">
            <navigation-bar />
        </div>
       <div class="columns">
        <div class="column">
            <user-badge user="`)
	//line todopage.qtpl:24
	qw422016.E().V(string(p.UserJSON))
	//line todopage.qtpl:24
	qw422016.N().S(`"/>
        </div>
        <div class="column is-three-quarters">
            <p class="title is-5">
                `)
	//line todopage.qtpl:28
	qw422016.E().S(p.Todo.Name)
	//line todopage.qtpl:28
	qw422016.N().S(`
            </p>
            <div class="content">
                `)
	//line todopage.qtpl:31
	qw422016.N().S(p.Todo.Content)
	//line todopage.qtpl:31
	qw422016.N().S(`
            </div>
        </div>
       </div>
    </div>
`)
//line todopage.qtpl:36
}

//line todopage.qtpl:36
func (p *TodoPage) WriteBody(qq422016 qtio422016.Writer) {
	//line todopage.qtpl:36
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line todopage.qtpl:36
	p.StreamBody(qw422016)
	//line todopage.qtpl:36
	qt422016.ReleaseWriter(qw422016)
//line todopage.qtpl:36
}

//line todopage.qtpl:36
func (p *TodoPage) Body() string {
	//line todopage.qtpl:36
	qb422016 := qt422016.AcquireByteBuffer()
	//line todopage.qtpl:36
	p.WriteBody(qb422016)
	//line todopage.qtpl:36
	qs422016 := string(qb422016.B)
	//line todopage.qtpl:36
	qt422016.ReleaseByteBuffer(qb422016)
	//line todopage.qtpl:36
	return qs422016
//line todopage.qtpl:36
}

//line todopage.qtpl:38
func (p *TodoPage) StreamCSSExternal(qw422016 *qt422016.Writer) {
	//line todopage.qtpl:38
	qw422016.N().S(`
`)
//line todopage.qtpl:39
}

//line todopage.qtpl:39
func (p *TodoPage) WriteCSSExternal(qq422016 qtio422016.Writer) {
	//line todopage.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line todopage.qtpl:39
	p.StreamCSSExternal(qw422016)
	//line todopage.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line todopage.qtpl:39
}

//line todopage.qtpl:39
func (p *TodoPage) CSSExternal() string {
	//line todopage.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
	//line todopage.qtpl:39
	p.WriteCSSExternal(qb422016)
	//line todopage.qtpl:39
	qs422016 := string(qb422016.B)
	//line todopage.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
	//line todopage.qtpl:39
	return qs422016
//line todopage.qtpl:39
}

//line todopage.qtpl:41
func (p *TodoPage) StreamScriptExternal(qw422016 *qt422016.Writer) {
	//line todopage.qtpl:41
	qw422016.N().S(`
`)
//line todopage.qtpl:42
}

//line todopage.qtpl:42
func (p *TodoPage) WriteScriptExternal(qq422016 qtio422016.Writer) {
	//line todopage.qtpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line todopage.qtpl:42
	p.StreamScriptExternal(qw422016)
	//line todopage.qtpl:42
	qt422016.ReleaseWriter(qw422016)
//line todopage.qtpl:42
}

//line todopage.qtpl:42
func (p *TodoPage) ScriptExternal() string {
	//line todopage.qtpl:42
	qb422016 := qt422016.AcquireByteBuffer()
	//line todopage.qtpl:42
	p.WriteScriptExternal(qb422016)
	//line todopage.qtpl:42
	qs422016 := string(qb422016.B)
	//line todopage.qtpl:42
	qt422016.ReleaseByteBuffer(qb422016)
	//line todopage.qtpl:42
	return qs422016
//line todopage.qtpl:42
}
